import { Inter } from "next/font/google";
import "./globals.css";
import LeftSidebar from "@/components/left-sidebar";
import RightSidebar from "@/components/right-sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex items-start justify-between`}>
        <LeftSidebar />
        <main className="flex-grow w-full h-full">{children}</main>
        <RightSidebar />
      </body>
    </html>
  );
}
